[package]
name = "bevy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cecs = { path = "../cecs/" }
bevy_ecs = "0.6"
num_cpus = "1.13"
bevy_tasks = "0.6"